chatbotSample = [
    "Học phí của học sinh lớp 10 trường là bao nhiêu?",
    "Những đối tượng nào được miễn giảm học phí?",
    "Quy trình xin miễn giảm học phí diễn ra như thế nào?",
    "Học phí có được điều chỉnh hàng năm không?",
    "Học sinh lớp 10 cần đóng các khoản phí nào ngoài học phí?",
    "Phí mua đồng phục của trường thường dao động ở mức nào?",
    "Sách giáo khoa và tài liệu học tập có phải tự mua không?",
    "Có bắt buộc đóng phí xây dựng trường không?",
    "Phí vệ sinh và bảo trì cơ sở vật chất có tính vào học phí không?",
    "Nhà trường có thu các khoản phí như nước uống hay bảo hiểm y tế không?",
    "Những khoản thu tự nguyện được quy định như thế nào?",
    "Nếu phụ huynh không đồng ý đóng các khoản tự nguyện, học sinh có bị ảnh hưởng không?",
    "Các khoản thu của trường có được công khai không?",
    "Các khoản thu đầu năm học có được thu dồn một lần không?",
    "Nhà trường có chính sách hoàn trả tiền nếu học sinh chuyển trường không?",
    "Có chương trình học bổng nào hỗ trợ học phí cho học sinh lớp 10 không?",
    "Những học sinh thuộc gia đình khó khăn có được hỗ trợ phí không?",
    "Làm thế nào để xin trợ cấp học phí?",
    "Nếu gặp khó khăn về tài chính, có thể chia nhỏ số lần đóng tiền không?",
    "Nếu học sinh học thêm môn tự chọn, có phải đóng phí riêng không?",
    "Nếu học sinh nghỉ học giữa kỳ, có được hoàn lại học phí không?",
    "Có phí nào phát sinh trong quá trình học mà phụ huynh cần lưu ý không?",
    "Có thể đóng học phí qua các phương thức trực tuyến không?",
    "Nếu quên đóng học phí, có bị phạt không?",
    "Nhà trường có chính sách hỗ trợ phí cho học sinh giỏi không?",
    "Thời gian học của trường bắt đầu và kết thúc lúc mấy giờ?",
    "Lớp học có sử dụng máy chiếu hoặc các thiết bị hiện đại không?",
    "Sĩ số trung bình của mỗi lớp là bao nhiêu?",
    "Có quy định về đồng phục hằng ngày không?",
    "Phòng học có quạt hoặc điều hòa không?",
    "Quy định và nội quy của trường?",
    "Có được mang điện thoại vào lớp không?",
    "Có được sử dụng tai nghe hoặc laptop trong giờ học không?",
    "Những hình thức xử lý kỷ luật khi vi phạm nội quy là gì?",
    "Các môn học bắt buộc trong chương trình lớp 10 là gì?",
    "Lịch học phụ đạo và bồi dưỡng được tổ chức vào lúc nào?",
    "Trường có thư viện không?",
    "Phòng thí nghiệm cho môn Hóa, Lý, Sinh được trang bị ra sao?",
    "Khu thể dục thể thao của trường có đủ rộng không?",
    "Nhà vệ sinh của trường có sạch sẽ và đầy đủ không?",
    "Có khu vực tự học hoặc phòng sinh hoạt chung không?",
    "Trường có bao nhiêu câu lạc bộ để tham gia?",
    "Làm thế nào để đăng ký tham gia câu lạc bộ?",
    "Có các cuộc thi hay sự kiện gì để học sinh thể hiện tài năng không?",
    "Tham gia hoạt động ngoại khóa có được tính điểm cộng rèn luyện không?",
    "Giáo viên có hỗ trợ học sinh ngoài giờ học không?",
    "Làm thế nào để liên hệ với giáo viên nếu cần?",
    "Đội ngũ cố vấn tâm lý của trường có thường xuyên hỗ trợ không?",
    "Nếu gặp vấn đề khó khăn trong lớp, nên báo với ai?",
    "Trường có chỗ để xe đạp hoặc xe máy không?",
    "Làm thế nào để báo cáo các trường hợp mất cắp trong trường?",
    "Có buổi định hướng cho học sinh lớp 10 mới nhập học không?",
    "Học sinh lớp 10 có được ghép nhóm với các bạn cũ không?",
    "Làm thế nào để làm quen với các bạn cùng lớp nhanh hơn?",
    "Có chương trình cố vấn từ anh chị lớp trên cho học sinh mới không?",
    "Học sinh mới có được tư vấn chọn lớp theo sở thích không?",
    "Trường có tổ chức tham quan thực tế hay không?",
    "Có chương trình giao lưu với các trường khác không?",
    "Học sinh có được tham gia các kỳ thi học sinh giỏi từ lớp 10 không?",
    "Trường có tổ chức dạy nghề hoặc định hướng nghề nghiệp không?",
    "Học sinh có thể tham gia các hoạt động thiện nguyện của trường không?",
    "Trường THPT Ung Văn Khiêm được thành lập vào năm nào?",
    "Trường nằm ở vị trí cụ thể nào tại An Giang?",
    "Cơ sở vật chất của trường có hiện đại không",
    "Trường có bao nhiêu lớp học mỗi khối?",
    "Điều kiện để được nhận vào học tại trường THPT Ung Văn Khiêm là gì?",
    "Trường có chương trình xét tuyển hay chỉ thi tuyển?",
    "Trường có giảng dạy các môn chuyên không?",
    "Trường có tổ chức học phụ đạo hoặc bồi dưỡng không?",
    "Trường có sân đá bóng không?",
    "Phòng thí nghiệm của trường có đủ trang thiết bị không?",
    "Trường có phòng tin học hiện đại không?",
    "Có được ăn uống trong lớp hoặc khuôn viên trường không?",
    "Trường có hỗ trợ học sinh đăng ký các kỳ thi chứng chỉ quốc tế không?",
    "Điểm chuẩn vào trường năm ngoái là bao nhiêu?",
    "Trường có yêu cầu điểm từng môn không?",
    "Có cần tham gia bài kiểm tra đầu vào không?",
    "Trường có nhận học sinh trái tuyến không?",
    "Học sinh cần chuẩn bị giấy tờ gì khi đăng ký?",
    "Có yêu cầu về hạnh kiểm của học sinh không?",
    "Học sinh có cần đạt thành tích học tập xuất sắc mới được tuyển không?",
    "Thời gian tuyển sinh chính thức là khi nào?",
    "Trường có xét học bạ không?",
    "Học sinh quốc tế có thể đăng ký không?",
    "Điểm ưu tiên khu vực được tính như thế nào?",
    "Trường có nhận học sinh chuyển cấp giữa kỳ không?",
    "Có xét tuyển nguyện vọng 2 không?",
    "Có yêu cầu về điểm ngoại ngữ không?",
    "Nếu trượt nguyện vọng 1, có được xét nguyện vọng khác không?",
    "Có giới hạn độ tuổi nhập học không?",
    "Trường có nhận học sinh đã từng lưu ban không?",
    "Có chế độ ưu tiên cho con em giáo viên không?",
    "Nếu hộ khẩu ở nơi khác, tôi có thể nộp hồ sơ không?",
    "Cần đạt bao nhiêu điểm để đảm bảo đậu vào trường?",
    "Học sinh có thể đăng ký học thử trước khi tuyển không?",
    "Trường có tổ chức các buổi tư vấn tuyển sinh không?",
    "Hạn chót nộp hồ sơ là ngày nào?",
    "Điểm cộng khu vực áp dụng như thế nào?",
    "Trường có chương trình đào tạo chuyên sâu nào không?",
    "Có các lớp chuyên Toán, Lý, Hóa không?",
    "Trường có chương trình học song ngữ không?",
    "Có chương trình học nghề song song không?",
    "Có thể học thêm ngoại ngữ nào ngoài tiếng Anh không?",
    "Chương trình học có áp lực không?",
    "Học sinh có được chọn môn học tự chọn không?",
    "Có các câu lạc bộ ngoại khóa nào?",
    "Trường có hỗ trợ ôn thi đại học không?",
    "Lịch học hàng ngày như thế nào?",
    "Trường có lớp học bồi dưỡng cho học sinh giỏi không?",
    "Trường có dạy thêm buổi tối không?",
    "Học sinh có được tham gia nghiên cứu khoa học không?",
    "Trường có hỗ trợ học sinh yếu kém không?",
    "Trường có tổ chức các kỳ thi học sinh giỏi không?",
    "Có học bổng cho học sinh xuất sắc không?",
    "Trường có giảng dạy lập trình và công nghệ không?",
    "Thời khóa biểu có cố định không?",
    "Trường có lớp học hè không?",
    "Có chương trình hỗ trợ học sinh định hướng nghề nghiệp không?",
    "Trường có đủ phòng thí nghiệm không?",
    "Lớp học có điều hòa không?",
    "Có khu nội trú cho học sinh không?",
    "Khuôn viên trường rộng bao nhiêu?",
    "Có thư viện không?",
    "Có phòng học riêng cho các môn thực hành không?",
    "Trường có sân thể thao không?",
    "Có phòng tập thể dục không?",
    "Trường có đảm bảo an ninh không?",
    "Có căng tin phục vụ trong giờ học không?",
    "Có khu vực tự học cho học sinh không?",
    "Môi trường học có thân thiện không?",
    "Trường có sử dụng công nghệ hiện đại trong giảng dạy không?",
    "Có wifi miễn phí trong trường không?",
    "Trường có lắp đặt camera an ninh không?",
    "Trường có khu vực nghỉ ngơi ngoài giờ học không?",
    "Học sinh có được sử dụng phòng máy tính không?",
    "Có nhà vệ sinh đạt tiêu chuẩn không?",
    "Có khu vực để xe an toàn không?",
    "Có máy chiếu trong các lớp học không?",
    "Có phòng y tế không?",
    "Khu vực xung quanh trường có an toàn không?",
    "Có phòng nghệ thuật và âm nhạc không?",
    "Học phí được quy định thế nào?",
    "Có các khoản phí nào ngoài học phí không?",
    "Có chính sách giảm học phí cho học sinh giỏi không?",
    "Trường có cấp học bổng không?",
    "Điều kiện để nhận học bổng là gì?",
    "Có hỗ trợ học phí cho học sinh nghèo không?",
    "Tiền ăn ở căn tin có đắt không?",
    "Các kỳ thi trong trường có phải trả phí không?",
    "Có phí bảo hiểm y tế không?",
    "Có miễn giảm cho con em gia đình chính sách không?",
    "Có hỗ trợ tài chính cho học sinh vùng sâu vùng xa không?",
    "Trường có quỹ khuyến học không?",
    "Nếu không đóng học phí đúng hạn có bị phạt không?",
    "Có thể trả góp học phí không?",
    "Học sinh tham gia nhiều câu lạc bộ có phải đóng phí thêm không?",
    "Có yêu cầu đóng phí bảo trì cơ sở vật chất không?",
    "Nếu rút hồ sơ có được hoàn lại học phí không?",
    "Chi phí học tăng cường các môn là bao nhiêu?",
    "Trường có chương trình tư vấn tâm lý không?",
    "Có hỗ trợ học sinh thi chuyển tiếp lên cấp 3 không?",
    "Học sinh giỏi có được tham gia các kỳ thi cấp quốc gia không?",
    "Có tổ chức các buổi định hướng nghề nghiệp không?",
    "Trường có kết nối với các trường đại học không?",
    "Trường có đội ngũ tư vấn học đường không?",
    "Trường có chương trình đào tạo STEM không?",
    "Có lớp phụ đạo riêng cho từng môn học không?",
    "Trường có những câu lạc bộ nào?",
    "Hãy liệt kê các tổ hợp môn",
    "Học tổ hợp 1 cần mua những loại sách nào?",
    "Học tổ hợp 2 cần mua những loại sách nào?",
    "Học tổ hợp 3 cần mua những loại sách nào?",
    "Học tổ hợp 4 cần mua những loại sách nào?",
    "Học tổ hợp 5 cần mua những loại sách nào?",
    "Học tổ hợp 6 cần mua những loại sách nào?",
    "Học tổ hợp 7 cần mua những loại sách nào?",
    "Đồ ăn ở căn tin có an toàn vệ sinh thực phẩm không?",
    "Trường có chính sách gì đối với học sinh hoàn cảnh khó khăn?",
    "Trường có cho phép học sinh học vượt lớp không?",
    "Trường có chương trình học giúp học sinh yếu kém cải thiện kết quả học tập không?",
    "Học sinh có thể học lại lớp nếu không đạt yêu cầu không?",
    "Có yêu cầu gì về hồ sơ y tế khi đăng ký tuyển sinh không?",
    "Trường có yêu cầu học sinh tham gia các hoạt động ngoại khóa bắt buộc không?",
    "Trường có tổ chức các hoạt động thể thao cho học sinh không?",
    "Trường có tổ chức các kỳ thi đánh giá năng lực học sinh không?",
    "Học sinh có thể chuyển giữa các lớp trong trường không?",
    "Trường có hỗ trợ học sinh trong việc định hướng nghề nghiệp sau khi tốt nghiệp không?",
    "Trường có cung cấp dịch vụ tư vấn học tập cho học sinh không?",
    "Trường có yêu cầu về sức khỏe để nhập học không?",
    "Trường có tổ chức các cuộc thi văn nghệ cho học sinh không?",
    "Trường có chương trình học cho học sinh có sở thích đặc biệt không?",
    "Học sinh có thể tham gia các cuộc thi học thuật trong và ngoài trường không?",
    "Trường có tổ chức các buổi chia sẻ về kỹ năng sống cho học sinh không?",
    "Trường có tổ chức các hoạt động học tập ngoài giờ chính khóa không?",
    "Trường có các chương trình học nhóm không?",
    "Trường có tổ chức các buổi hội thảo định hướng nghề nghiệp không?",
    "Trường có chương trình học đào tạo nghề song song với học phổ thông không?",
    "Học sinh có thể tham gia các lớp học kỹ năng nghề nghiệp không?",
    "Trường có hệ thống đánh giá học sinh theo tiêu chí nào?",
    "Trường có tổ chức các cuộc thi thể thao trong trường không?",
    "Trường có tổ chức các cuộc thi hùng biện cho học sinh không?",
    "Trường có tổ chức các cuộc thi vẽ hoặc nghệ thuật không?",
    "Trường có thể tổ chức các cuộc thi khoa học kỹ thuật cho học sinh không?",
    "Trường có tổ chức các cuộc thi thuyết trình cho học sinh không?",
    "Trường có tổ chức các buổi nói chuyện với các chuyên gia không?",
    "Trường có các lớp học dành riêng cho học sinh yếu kém không?",
    "Trường có quy định gì về đồng phục học sinh?",
    "Trường có yêu cầu học sinh tham gia các buổi học phụ đạo không?",
    "Trường có những yêu cầu nào về thái độ học tập của học sinh?",
    "Học sinh có thể tham gia các cuộc thi sáng tạo trong trường không?",
    "Trường có các buổi tư vấn riêng cho học sinh không?",
    "Trường có quy định gì về việc học sinh tham gia các hoạt động bên ngoài không?",
    "Trường có các chương trình học miễn phí cho học sinh không?",
    "Trường có các chương trình giúp học sinh phát triển khả năng làm việc nhóm không?",
    "Trường có các hoạt động giúp học sinh phát triển tư duy sáng tạo không?",
]


chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]